---
git:
  depth: 3
before_install:
  - openssl aes-256-cbc -K $encrypted_cd04acecb046_key -iv $encrypted_cd04acecb046_iv
    -in deploy_key.enc -out deploy_key -d
  - chmod 400 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - rm hugo_0.49_Linux-64bit.deb
script:
  - hugo version
  - cd src
  - mkdir -p content data layouts static themes archetypes # hugo requires the directory structure to exist
  - cd ..
  - hugo -s src/ -d ../public/
  - ls public/
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh public
  on:
    branch: master
notifications:
  email:
    on_success: change
    on_failure: change
