---
baseURL: &baseURL "https://stephengregory.github.io/"
defaultContentLanguage: "en"
disqusShortname: stephengregorynl
metaDataFormat: "yaml"
paginate: 10
theme: "casper"
title: "Stephen Gregory"
watch: true
menu:
    main:
        - name: "Art"
          url: "/art"
        - name: "DIY"
          url: "/diy"

params:
    author: "Stephen Gregory"
    authorlocation: "Newfoundland, Canada"
    authorwebsite: *baseURL
    bio: ""
    cover: "images/cover_peace_bridge.jpg"
    customCSS:
      - "css/sg.css"
    description: "Engineer. Photographer. Music enthusiast. Wizard."
    email: "stephengregorynl@gmail.com"
    flickrName: "stephengregorynl"
    githubName: "stephengregory"
    instagramName: "stephengregory"
    logo: "images/logo.png"
    linkedinName: "stephengregorynl"
    excludesectionsfromhome:
        - notes-for-anna
    twitterName: "hedz_09"

---
